Feat/api#2
chlyNiklas/r2 pull request #8
Opened 2024-11-29 10:53 UTC by chlyNiklas

Proccessor's api implementation

2024-12-06 06:44 UTC, Jakoshi45 requested changes

2024-12-06 06:44 UTC, Jakoshi45 commented on processor/api.py
> +            print(offset)
these will be removed later right?

2024-12-06 06:44 UTC, Jakoshi45 commented on processor/api.py
>                  print(f"An error occurred: {e}")
is the f before the quotation marks intentional?

2024-12-06 06:44 UTC, Jakoshi45 commented on processor/api.py
> +                print(e)
isn't this redundant?

2024-12-06 14:40 UTC, chlyNiklas commented on processor/api.py
>                  print(f"An error occurred: {e}")
Jes, this is for python formated strings

2024-12-06 14:44 UTC, chlyNiklas commented on processor/api.py
> +                print(e)
fixed

2024-12-06 14:44 UTC, chlyNiklas commented on processor/api.py
> +            print(offset)
fixed

2024-12-07 00:54 UTC, Jakoshi45 approved these changes

2024-12-07 16:23 UTC, merged